import Link from "next/link";

export default function PrivacyNoticePage() {
  return (
    <main className="docs-shell">
      <div className="docs-page">
        <section className="docs-hero plain">
          <p className="docs-kicker">Legal</p>
          <h1>Privacy Notice</h1>
          <p>
            FlashAlliance frontend is designed to minimize custodial data handling. Most interaction data is public blockchain
            data generated by user-signed transactions.
          </p>
        </section>

        <article className="docs-prose">
          <h2>1. Data processed by frontend</h2>
          <ul>
            <li>Wallet address used for connection and contract calls.</li>
            <li>Public chain data read from RPC/subgraph providers.</li>
            <li>Optional client-side browser storage for UI convenience states.</li>
          </ul>

          <h2>2. Data we do not claim to protect onchain</h2>
          <p>
            Onchain transactions, addresses, and event logs are public by design. Avoid sharing personally identifying details
            through wallet-linked public actions.
          </p>

          <h2>3. Third-party services</h2>
          <p>
            RPC providers, explorers, wallet extensions, and subgraph providers may process metadata according to their own
            policies.
          </p>

          <h2>4. Contact</h2>
          <p>
            For privacy or security concerns, use the project contact listed in the repository and reporting policy.
          </p>
        </article>

        <section className="docs-callout plain">
          <h3>Related docs</h3>
          <p>
            Review <Link href="/docs/status">Status</Link>, <Link href="/docs/release">Release Readiness</Link>, and{" "}
            <Link href="/docs/rules">Rules of Use</Link> for operational context.
          </p>
        </section>
      </div>
    </main>
  );
}
